#' return a data set used for testing
#'
#' @return data frame
#'
#' @examples
#' df <- create_test_data()
create_test_data <- function()
{
  library(palmerpenguins)
  palmerpenguins::penguins
}

#' verify a PCA plot generated by KMeans with centers=n_clusters
#'
#' @param p PCA plot
#' @param n_cluster number of clusters
#'
#' @return raise exception if expect_equal fails
#'
#' @examples
#' library(palmerpenguins)
#' df <- penguins
#' results <- explore_KMeans_clustering(df, c(2, 3))
#' verify_KMeans_plot(results[[1]], 2)
verify_KMeans_plot <- function(p, n_cluster){
  expect_equal(p$labels$title, paste0("PCA Plot - KMeans with", n_cluster," centers"))
  expect_equal(nlevels(p$data$groups), n_cluster)
}
