#' fit and plot K-Means, DBScan clustering algorithm on the dataset
#'
#' @param df dataframe
#' @param numeric_cols vector of numeric columns' names, default is NULL, all numeric columns will be used
#' @param hyperparameter_dict dictionary of hyperparameters to be used, default is NULL, a default set of hyperparameters will be used
#'
#' @return a dictionary with each key = a clustering model name, value = list of plots generated by that model
#'
#' @examples
#' \dontrun{
#' explore_clustering(df)
#' }
explore_clustering <- function(df, numeric_cols=NULL, hyperparameter_dict=NULL){

}
