#' fit and plot K-Means, DBScan clustering algorithm on the dataset
#'
#' @param df the dataset
#' @param numeric_cols a list of numeric columns' names
#' @param hyperparameter_dict a dictionary of hyperparameters to be used
#'
#' @return a dictionary with each key = a clustering model name, value = list of plots generated by that model
#'
#' @examples
#' df <- read_csv("data_file.csv")
#' numeric_cols <- c("col1", "col2")
#' explore_clustering(df)
explore_clustering <- function(df, numeric_cols, hyperparameter_dict){

}
